---
title: "Docker Hub Basics"
author: Shree Madan
date: 2022-02-24
output: github_document
time: 15
reading: 
---

*Purpose*: When starting to use Docker, Docker Hub is the way to engage with
external resources and other people's containers. This is an explanation of
those interactions.

Additionally, we'll pull our first container which is set up the structure for
using containers in the future.

*Reading*: McGuire, Dennis, Schwartz pg. 43-48

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

<!-- -------------------------------------------------- -->

__q0__ Make a free Docker Hub account:

Following the instructions at https://hub.docker.com/ to make a free account.

Docker Hub is the space to access pre-built containers which you can use to 
build your own containers. An example of this would be pulling an ubuntu container
to your own container and then building software to run on it.

__q1__ Interacting with Docker Hub from the command line

*Hint*: Most command line directives have the same format COMMAND SUBCOMMAND 
(ex. docker run "container name" or docker image build)

```{bash docker-run-ex-1}
# NOTE: No need to edit; run this to try out Docker
# solution-begin
docker run hello-world
# solution-end
```

This should give you the output "Hello from Docker!"

Later in this exercise, we will discuss the process which Docker took to generate the message

__q2__ Using the Docker Hub website

On https://hub.docker.com/ search for the Hello-World container. 

Using Docker Hub like this provides more through documentation for pre-built 
containers. They often include information about running the container and the 
necessary software or arguments. Identify a few of the simple and shared tags on 
the website below as well as other observations of the information on the site.

**Observations**:

simple tags - 
shared tags - 

__q3__ How does Docker process command line calls to Docker Hub

Unable to find image 'hello-world:latest' locally 
latest: Pulling from library/hello-world 
1b930d010525: Pull complete 
Digest: sha256:4fe721ccc2e8dc7362278a29dc660d833570ec2682f4e 
4194f4ee23e415e1064 
Status: Downloaded newer image for hello-world:latest

This should be the output you see while running the Hello-World docker container.
Let's break down some of these lines to get a better understanding of what the computer
is running. 

Unable to find image 'hello-world:latest' locally --> checks if the container 
already exists locally if not the Docker client will contact the Docker daemon.

From here there are a few steps built into the run command (when using pre-built containers).

It will pull the image from Docker Hub which it then uses to create a new container.
The output we see will be produced by that container.

However to see that output in the terminal the Docker daemon needs to stream it 
to the client which then send it to the terminal.